### ISSUE TITLE
meteor add-platform ios does not work if app name starts with a number

### ISSUE THREAD

**Issue by mpuncel** [Urigo/meteor-ionic#44] opened 2015-06-01 06:02 UTC
Error looks like 

```
$ meteor add-platform ios
Error creating Cordova prject: Error running
/Users/mpuncel/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
App id contains a reserved word, or is not a valid identifier.
```

To reproduce:

```
$ meteor create 3xperiment
$ cd 3xperiment
$ meteor add urigo:ionic
$ meteor add-platform ios
```

Subsequent attempts fail because it thinks the platform is already added. `meteor run ios` fails with the original error

**Comment by mpuncel** [comment] 2015-06-01 06:07
This error does not happen with vanilla ionic or cordova

**Comment by Urigo** [comment] 2015-06-06 17:43
yes you are right, this is a duplicate of this issue:
https://github.com/meteor/meteor/issues/2868

**Closed by Urigo** 2015-06-06 17:43 UTC
